name: lazyloadgetx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  #Google
  cupertino_icons: ^1.0.2
  #State Management
  get: ^4.6.1
  #JsonConverter
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  #NetworkHelper
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
flutter:
  uses-material-design: true